namespace TerminalQuest.Mcp
{
    /// <summary>
    /// Ordinary English words, drawn at random to give the narrator a starting point it did not
    /// choose.
    /// <para>
    /// Nothing here generates anything - it only picks. Asked for somewhere new, a model samples
    /// from its own priors and produces another tavern, another ruined temple, another misty
    /// crossroads. A word it did not pick forces the starting point outside those priors, and
    /// joining <c>brackish</c> to <c>ledger</c> into a flooded tax office full of smugglers is work
    /// the model is good at once it has been made to start somewhere unfamiliar.
    /// </para>
    /// <para>
    /// The lists are deliberately mundane and deliberately not of the genre. Seeding with
    /// <c>rune</c>, <c>barrow</c> or <c>ancient</c> would hand back the very cliches this exists to
    /// escape: the distance between the word and the setting is the whole mechanism. For the same
    /// reason there are no proper nouns, and nothing so modern that a model could not help placing
    /// it literally - a word that cannot be a seed costs more than it gives.
    /// </para>
    /// <para>
    /// Held as C# rather than a data file, following <see cref="Saves.ClassTemplates"/> and
    /// <see cref="Settings.ClaudeModels"/>: there is nothing to deploy, nothing to find at runtime,
    /// and no missing-resource path to handle. Written one word per line in a raw literal rather
    /// than a quoted array so the lists stay editable as lists. Both are sorted, which with no test
    /// project is the only thing that makes a duplicate visible to whoever is reading.
    /// </para>
    /// </summary>
    internal static class WordBank
    {
        /// <summary>
        /// Concrete and countable before abstract, and common enough to picture without pausing.
        /// Trades, buildings, materials, weather, landscape, food, animals, plants, garments and
        /// containers, plus a minority of graspable abstractions - a <c>grudge</c> and a <c>debt</c>
        /// seed a person as readily as a <c>kettle</c> seeds a room.
        /// </summary>
        private const string NounSource = """
            abacus
            acorn
            alcove
            alley
            almshouse
            anchor
            anvil
            apiary
            apron
            aqueduct
            arbour
            archway
            ash
            attic
            auction
            awning
            axle
            badge
            bailiff
            bakery
            balcony
            ballast
            bandage
            bannister
            barge
            bark
            barley
            barn
            barrel
            basin
            basket
            bathhouse
            beacon
            beam
            bedrock
            beehive
            bell
            bellows
            bench
            bequest
            berry
            bilge
            blanket
            blister
            blossom
            bolt
            bonfire
            boot
            border
            bough
            boundary
            bracket
            braid
            bramble
            brand
            brass
            bread
            breeze
            brewery
            brick
            bridle
            broom
            bruise
            bucket
            bundle
            burrow
            butcher
            buttress
            cabbage
            cable
            cage
            cairn
            calendar
            candle
            canvas
            canyon
            cargo
            carpenter
            cart
            cascade
            cask
            cauldron
            causeway
            cavern
            cedar
            cellar
            cement
            chain
            chalk
            chapel
            charcoal
            chimney
            chisel
            cistern
            clamp
            clasp
            clay
            cleaver
            cliff
            cloak
            clot
            clover
            coal
            cobbler
            cobweb
            coffer
            coil
            collar
            column
            comb
            compass
            conduit
            cooper
            cord
            cornice
            corridor
            cough
            county
            courtyard
            cove
            crate
            crease
            creek
            crest
            crevice
            crib
            crop
            crossing
            crowbar
            crumb
            crust
            crutch
            cupboard
            curfew
            current
            cushion
            custom
            dairy
            dam
            debt
            deed
            delta
            den
            dent
            dike
            ditch
            dock
            dowry
            drain
            draught
            dregs
            drift
            drought
            drum
            dune
            dust
            dye
            eaves
            echo
            eddy
            elbow
            elder
            embankment
            ember
            envelope
            errand
            estuary
            ewe
            exchange
            fable
            factory
            famine
            fang
            farrier
            fathom
            feather
            fence
            fern
            ferry
            fetter
            feud
            fiddle
            field
            figurehead
            filament
            fissure
            flagstone
            flask
            fleece
            flint
            flock
            floodplain
            flour
            flue
            foghorn
            foothill
            forge
            fossil
            foundry
            fountain
            fracture
            frame
            freckle
            frost
            funnel
            furnace
            furrow
            gable
            gale
            gallery
            gallows
            garland
            garret
            gasp
            gate
            gauge
            gauze
            gearing
            ginger
            girder
            glacier
            glade
            glass
            glove
            glue
            gorge
            gossip
            gourd
            granary
            granite
            grate
            gravel
            grief
            grindstone
            groove
            grotto
            grove
            grudge
            gulch
            gully
            gutter
            hail
            halter
            hamlet
            hammer
            hamper
            harbour
            harness
            harvest
            hatch
            hawthorn
            haystack
            headland
            hearth
            heather
            hedge
            heirloom
            helm
            hem
            herd
            hermit
            hinge
            hive
            hoard
            hoist
            hollow
            honey
            hood
            hoof
            hook
            hopper
            hostel
            hunch
            husk
            hut
            ice
            incline
            infirmary
            ingot
            inkwell
            inlet
            inquest
            insult
            iron
            ivy
            jar
            jaw
            jetty
            joist
            journal
            journey
            jug
            junction
            juniper
            keel
            kelp
            kennel
            kernel
            kettle
            key
            kiln
            kindling
            knapsack
            knot
            knuckle
            labyrinth
            lace
            ladder
            lagoon
            landslide
            lantern
            lard
            larder
            latch
            lathe
            lattice
            laundry
            lease
            ledge
            ledger
            leech
            levee
            lever
            lichen
            lid
            lighthouse
            lime
            linen
            lint
            lintel
            loaf
            lock
            lodge
            loft
            log
            loom
            lung
            lye
            mallet
            malt
            mangrove
            mantle
            marble
            mare
            marsh
            mask
            mast
            mattress
            meadow
            meal
            meander
            medallion
            membrane
            mercy
            mesh
            midden
            mildew
            milestone
            mill
            millstone
            mineshaft
            mint
            mire
            mirror
            mist
            mitten
            moat
            monsoon
            moor
            mortar
            moss
            moth
            mould
            mound
            mule
            muzzle
            nail
            needle
            nest
            net
            nettle
            niche
            notch
            notice
            nursery
            nut
            oak
            oar
            oath
            oats
            obelisk
            offal
            oil
            ointment
            orchard
            ore
            oven
            overhang
            owl
            ox
            oyster
            paddock
            padlock
            pail
            palisade
            pallet
            pane
            pantry
            parapet
            parcel
            pardon
            parish
            partition
            pasture
            patch
            path
            pauper
            pavement
            pawn
            peat
            pebble
            pediment
            peg
            pelt
            pendulum
            pension
            pepper
            pew
            pier
            pigment
            pike
            pillar
            pincers
            pinion
            pipe
            pitch
            pivot
            plank
            plaster
            plateau
            plinth
            plough
            plume
            poacher
            pole
            pollen
            pond
            porch
            portico
            post
            pothole
            poultice
            prairie
            press
            privy
            prow
            pulley
            pulp
            pump
            purse
            quarantine
            quarry
            quay
            quicksand
            quill
            quilt
            quota
            raft
            rafter
            rail
            rake
            ramp
            rampart
            ranch
            rasp
            ration
            ravine
            reed
            reef
            reel
            refuge
            register
            reins
            rennet
            rent
            resin
            ribbon
            ridge
            rift
            rind
            rivet
            roost
            rope
            rot
            rowan
            rubble
            rudder
            rug
            rumour
            rushes
            rust
            rye
            sack
            saddle
            sailcloth
            salt
            sand
            sapling
            sash
            sawdust
            scaffold
            scale
            scar
            scarecrow
            scissors
            scrap
            screen
            scythe
            seam
            sediment
            seed
            sentry
            sermon
            sewer
            shackle
            shale
            shallows
            shard
            shawl
            shed
            sheep
            sheet
            shelf
            shepherd
            shingle
            shipyard
            shoal
            shovel
            shrine
            shroud
            shutter
            sickle
            sieve
            silo
            silt
            sinew
            sinkhole
            skiff
            skillet
            skylight
            slab
            slate
            sledge
            sleet
            sling
            sluice
            smock
            smoke
            snare
            soap
            socket
            soot
            spade
            span
            spice
            spike
            spindle
            spire
            splint
            splinter
            spool
            spout
            sprig
            spur
            stable
            stack
            staff
            stain
            stairwell
            stake
            stall
            stanchion
            starch
            statue
            stave
            steam
            steeple
            stem
            stew
            stile
            stilt
            sting
            stitch
            stockade
            stone
            stool
            storeroom
            stove
            strap
            straw
            stream
            stump
            sty
            summit
            sump
            surplus
            swamp
            swarm
            sweat
            swell
            swill
            sycamore
            table
            tack
            tallow
            tangle
            tanner
            tar
            tarp
            tassel
            teak
            tenant
            tendon
            tenement
            tether
            thatch
            thicket
            thimble
            thistle
            thorn
            thread
            threshold
            thumb
            thunder
            tide
            timber
            tin
            tinder
            toll
            tomb
            tongs
            torrent
            tower
            trace
            track
            trade
            trail
            trap
            trapdoor
            trawl
            tray
            treadle
            trench
            trestle
            tribute
            trickle
            trough
            trowel
            truce
            trunk
            tub
            tuft
            tunnel
            turf
            turnip
            tusk
            twig
            twine
            udder
            undergrowth
            upholstery
            urn
            valley
            valve
            vane
            vat
            vault
            veil
            vein
            vellum
            veneer
            verge
            vessel
            vestibule
            viaduct
            vine
            vinegar
            vise
            vow
            wafer
            wagon
            wainscot
            waist
            wake
            wall
            ward
            warehouse
            warp
            wart
            washboard
            wasp
            waterfall
            waterwheel
            wattle
            wax
            weathervane
            weave
            wedge
            weir
            well
            wharf
            wheat
            wheel
            whetstone
            whistle
            wick
            willow
            winch
            windmill
            window
            wire
            wool
            workshop
            worm
            wound
            wreath
            wreck
            wrist
            yard
            yarn
            yeast
            yew
            yield
            yoke
            zinc
            """;

        /// <summary>
        /// Sensory, physical or temperamental. Bare judgements - <c>good</c>, <c>nice</c>,
        /// <c>strange</c> - are left out on purpose: they carry no image, so they seed nothing and
        /// only dilute the draw.
        /// </summary>
        private const string AdjectiveSource = """
            abandoned
            abrupt
            acrid
            adjacent
            adrift
            aimless
            airless
            ajar
            alkaline
            aloof
            amber
            ample
            anxious
            arid
            ashen
            austere
            awkward
            baggy
            bald
            bandaged
            barbed
            bare
            barren
            bashful
            bearded
            bitter
            blackened
            bland
            blistered
            bloated
            blotchy
            blunt
            blustery
            boggy
            boisterous
            bolted
            bony
            bottomless
            boxy
            brackish
            braided
            brash
            brazen
            breathless
            brisk
            bristly
            brittle
            broad
            bruised
            bubbling
            bulging
            bulky
            bumpy
            buoyant
            burnished
            bustling
            candid
            cantankerous
            capsized
            careworn
            cavernous
            chalky
            chapped
            charred
            cheap
            chewy
            chilly
            chipped
            choked
            churlish
            clammy
            clean
            clenched
            clipped
            cloudy
            clumsy
            coarse
            cobbled
            coiled
            cold
            collapsed
            communal
            compact
            congested
            contrary
            cooped
            corroded
            costly
            cracked
            cramped
            crooked
            crowded
            crumbling
            crusted
            curdled
            curt
            damp
            dappled
            darned
            dazzling
            deafening
            decrepit
            deep
            deliberate
            dented
            derelict
            deserted
            dilapidated
            dim
            dingy
            dishevelled
            disused
            docile
            dogged
            domed
            doughy
            downcast
            drafty
            drenched
            dried
            drooping
            drowsy
            dry
            dusty
            dwindling
            earnest
            echoing
            elastic
            elderly
            elevated
            embroidered
            empty
            encrusted
            endless
            engraved
            enormous
            evasive
            exposed
            faded
            faint
            fallow
            famished
            fastened
            fat
            feathered
            feeble
            fenced
            fermented
            fertile
            festering
            fetid
            fibrous
            fidgety
            filthy
            fine
            flaking
            flat
            flattened
            fleeting
            flimsy
            flooded
            floury
            fluted
            foggy
            forked
            formal
            fractured
            fragrant
            frayed
            freckled
            freezing
            fretful
            frosted
            frothy
            frozen
            furrowed
            fussy
            gangly
            gaping
            garbled
            gaunt
            gauzy
            generous
            genteel
            glassy
            glazed
            gleaming
            glossy
            glum
            gnarled
            grainy
            grand
            grasping
            grassy
            gravelly
            greasy
            greedy
            grimy
            gritty
            grizzled
            grooved
            gruff
            guarded
            gummy
            gusty
            guttural
            hairy
            halting
            hammered
            handmade
            hardened
            harsh
            haughty
            hazy
            headstrong
            heaped
            heavy
            hemmed
            hesitant
            hidden
            hoarse
            hollow
            honeyed
            hooded
            hooked
            humid
            hunched
            husky
            icy
            idle
            ill-fitting
            immense
            impatient
            inclined
            indoor
            infested
            inland
            insulated
            itchy
            jagged
            jaundiced
            jittery
            jointed
            jumbled
            keen
            knobbly
            knotted
            labelled
            lacquered
            laden
            lame
            lanky
            lashed
            lax
            leaden
            leafy
            leaky
            lean
            leathery
            leftover
            lengthy
            level
            lidded
            limp
            lined
            lingering
            listless
            littered
            lively
            loamy
            lofty
            loose
            lopsided
            loud
            low
            lumpy
            lush
            maimed
            mangled
            marbled
            marshy
            matted
            meagre
            measured
            meaty
            mended
            methodical
            mildewed
            milky
            mired
            misshapen
            misty
            mottled
            mouldy
            mounded
            muddy
            muffled
            muggy
            municipal
            murky
            mushy
            musty
            mute
            nailed
            narrow
            needy
            nervous
            nested
            nimble
            noisy
            nomadic
            notched
            numb
            oaken
            obedient
            oblique
            obstinate
            oily
            opaque
            open
            orderly
            ornate
            outspoken
            oval
            overcast
            overgrown
            overhanging
            overloaded
            packed
            padded
            painted
            pale
            panelled
            parched
            partitioned
            passable
            pasty
            patched
            patient
            paved
            peaked
            pebbled
            peeling
            peevish
            pendulous
            perched
            permanent
            pillared
            pitted
            plain
            planked
            plastered
            pleated
            pliant
            plump
            pocked
            polished
            ponderous
            porous
            portly
            potted
            powdery
            prickly
            private
            prompt
            propped
            pruned
            puckered
            puffy
            pulpy
            punctual
            pungent
            putrid
            quarrelsome
            quenched
            quick
            quiet
            quilted
            ragged
            rainy
            rancid
            rasping
            ratty
            ravenous
            raw
            reclusive
            reedy
            refitted
            reinforced
            remote
            rented
            repaired
            resinous
            restless
            ribbed
            ridged
            rimmed
            rinsed
            riveted
            roasted
            rocky
            roomy
            ropy
            rotten
            rough
            round
            rowdy
            rubbery
            rugged
            rumpled
            runny
            rusted
            rutted
            sagging
            salted
            salvaged
            sanded
            sandy
            sappy
            scabbed
            scalding
            scaly
            scant
            scarred
            scattered
            scorched
            scoured
            scraggly
            scrubbed
            scuffed
            sealed
            seamed
            seasoned
            secluded
            sedate
            seeping
            serrated
            severe
            shabby
            shaded
            shallow
            sharp
            shattered
            sheer
            shingled
            shorn
            short
            shredded
            shrill
            shrivelled
            shuttered
            sinewy
            singed
            sinking
            skewed
            slack
            slanted
            sleek
            slender
            slick
            slippery
            sloped
            sloppy
            slouching
            sludgy
            sluggish
            smoky
            smooth
            smothered
            snug
            soaked
            sodden
            soft
            soggy
            solitary
            sooty
            sour
            spacious
            sparse
            speckled
            spiked
            spindly
            splayed
            splintered
            spongy
            spotless
            sprawling
            springy
            squat
            squelching
            stacked
            stagnant
            stained
            stale
            starched
            starved
            steady
            steep
            sticky
            stiff
            stifling
            stilted
            stocky
            stony
            stooped
            stormy
            straggling
            straight
            strained
            stranded
            strapped
            stringy
            striped
            stubbled
            stubby
            studded
            stunted
            sturdy
            sullen
            sunken
            sunlit
            surly
            swampy
            sweltering
            swollen
            tacky
            talkative
            tangled
            tanned
            tapered
            tarnished
            tart
            tattered
            taut
            teeming
            tepid
            terraced
            thatched
            thick
            thin
            thorny
            thrifty
            throbbing
            thundery
            tidal
            tidy
            tight
            tiled
            timbered
            tinny
            tired
            toothless
            torn
            tough
            towering
            trampled
            tranquil
            translucent
            trellised
            trembling
            trim
            trodden
            tufted
            twisted
            unbolted
            uncombed
            uncut
            underfed
            undulating
            uneven
            unfinished
            unlit
            unpaved
            unruly
            unsteady
            untidy
            upended
            upright
            upturned
            useful
            vacant
            vaulted
            veined
            velvety
            ventilated
            verdant
            vinegary
            viscous
            vocal
            wakeful
            walled
            wandering
            warped
            wary
            washed
            wasteful
            watchful
            waterlogged
            watery
            wavy
            waxy
            weathered
            webbed
            wedged
            weedy
            weepy
            weighted
            welded
            wet
            wheezing
            whiskered
            whitewashed
            wide
            widowed
            wilted
            windswept
            windy
            wiry
            withered
            wobbly
            woollen
            wordy
            worn
            woven
            wrinkled
            wry
            yawning
            yeasty
            yellowed
            yielding
            young
            zealous
            """;

        public static readonly string[] Nouns = Split(NounSource);

        public static readonly string[] Adjectives = Split(AdjectiveSource);

        /// <summary>
        /// <paramref name="count"/> words from <paramref name="words"/>, never the same one twice.
        /// </summary>
        /// <remarks>
        /// Drawing without replacement matters more than it looks: three of the same word reads to
        /// the model as emphasis rather than as an accident, and a repeated seed is one seed.
        /// <para>
        /// Rejection sampling rather than a shuffle because the caller has already clamped the count
        /// to single figures against a list of hundreds, so a collision is rare and a partial
        /// shuffle would copy the whole index array to save nothing.
        /// </para>
        /// </remarks>
        /// <param name="words">The list to draw from.</param>
        /// <param name="count">How many to take. Clamped to what the list can supply.</param>
        /// <param name="random">
        /// Where the draws come from. A parameter rather than a static reached for in here, for the
        /// same reason as <see cref="Saves.Dice.TryRoll"/>: seeding a session, or replaying one,
        /// stays a change at the call site.
        /// </param>
        public static IReadOnlyList<string> Pick(string[] words, int count, Random random)
        {
            ArgumentNullException.ThrowIfNull(words);
            ArgumentNullException.ThrowIfNull(random);

            var wanted = Math.Clamp(count, 1, words.Length);

            var chosen = new List<string>(wanted);
            var taken = new HashSet<int>(wanted);

            while (chosen.Count < wanted)
            {
                var index = random.Next(words.Length);

                if (taken.Add(index))
                {
                    chosen.Add(words[index]);
                }
            }

            return chosen;
        }

        /// <summary>
        /// One word per line into an array. <see cref="StringSplitOptions.TrimEntries"/> also takes
        /// care of the carriage return, so the lists survive a checkout with either line ending.
        /// </summary>
        private static string[] Split(string source) =>
            source.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
    }
}
